### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by ctheune** [trbs/fallocate#5]
Hi,

I wanted to use this with backy, but that didn't work as Python 3 isn't supported yet. Superficially, the "file" type is gone. But then again the C API has changed incompatibly, too.

I ended up with:

```
Traceback (most recent call last):
  File "/Users/ctheune/Code/backy/src/backy/sources/ceph/tests/test_diff.py", line 195, in test_integrate_stops_on_broken_data_record
    diff.integrate(target, 'fromsnapshot', 'tosnapshot')
  File "/Users/ctheune/Code/backy/src/backy/sources/ceph/diff.py", line 153, in integrate
    fallocate(target.fileno(), target.tell(), record.length)
  File "/Users/ctheune/Code/backy/eggs/fallocate-1.4.0-py3.4-macosx-10.6-x86_64.egg/fallocate/__init__.py", line 10, in fallocate
    return _fallocate(fd, mode, offset, len)
OSError: [Errno 22] Invalid argument
```

**Comment by trbs** [comment]
Hmm it should work with Python3 on my machine the tests also pass with Python3. Could you make a test for this problem so we can fix it ?
